# Generated by Django 4.2.4 on 2023-10-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('rarity', models.CharField(max_length=16)),
                ('tooltip', models.CharField(max_length=255)),
                ('crafting', models.JSONField(blank=True, default=dict, null=True)),
                ('item_type', models.CharField(default='armor', max_length=16)),
                ('item_slot', models.CharField(max_length=16)),
                ('attr_bonus', models.JSONField(default=dict)),
                ('attr_multi', models.JSONField(default=dict)),
                ('physical_armor', models.IntegerField()),
                ('magical_armor', models.IntegerField()),
                ('enhancements', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('rarity', models.CharField(max_length=16)),
                ('tooltip', models.CharField(max_length=255)),
                ('crafting', models.JSONField(blank=True, default=dict, null=True)),
                ('item_type', models.CharField(default='material', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('rarity', models.CharField(max_length=16)),
                ('tooltip', models.CharField(max_length=255)),
                ('crafting', models.JSONField(blank=True, default=dict, null=True)),
                ('item_type', models.CharField(default='recipe', max_length=16)),
                ('recipe_for', models.CharField(max_length=64)),
                ('recipe_materials', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('rarity', models.CharField(max_length=16)),
                ('tooltip', models.CharField(max_length=255)),
                ('crafting', models.JSONField(blank=True, default=dict, null=True)),
                ('item_type', models.CharField(default='rune', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('rarity', models.CharField(max_length=16)),
                ('tooltip', models.CharField(max_length=255)),
                ('crafting', models.JSONField(blank=True, default=dict, null=True)),
                ('item_type', models.CharField(default='weapon', max_length=16)),
                ('item_slot', models.JSONField(default=list)),
                ('attr_bonus', models.JSONField(default=dict)),
                ('attr_multi', models.JSONField(default=dict)),
                ('physical_armor', models.IntegerField(blank=True, null=True)),
                ('magical_armor', models.IntegerField(blank=True, null=True)),
                ('enhancements', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
