# Generated by Django 4.2.4 on 2023-10-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='icon',
            field=models.ImageField(default='static/images/item-icons/armor-icons/placeholder.png', upload_to='static/images/item-icons/armor-icons'),
        ),
        migrations.AddField(
            model_name='material',
            name='icon',
            field=models.ImageField(default='static/images/item-icons/material-icons/placeholder.png', upload_to='static/images/item-icons/material-icons'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='icon',
            field=models.ImageField(default='static/images/item-icons/recipe-icons/placeholder.png', upload_to='static/images/item-icons/recipe-icons'),
        ),
        migrations.AddField(
            model_name='rune',
            name='icon',
            field=models.ImageField(default='static/images/item-icons/rune-icons/placeholder.png', upload_to='static/images/item-icons/rune-icons'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='icon',
            field=models.ImageField(default='static/images/item-icons/weapon-icons/placeholder.png', upload_to='static/images/item-icons/weapon-icons'),
        ),
    ]
