# Generated by Django 4.2.4 on 2023-10-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_armor_icon_material_icon_recipe_icon_rune_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='attr_bonus',
        ),
        migrations.RemoveField(
            model_name='armor',
            name='attr_multi',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='attr_bonus',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='attr_multi',
        ),
        migrations.AddField(
            model_name='armor',
            name='agility_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='armor',
            name='agility_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='armor',
            name='charisma_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='armor',
            name='charisma_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='armor',
            name='endurance_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='armor',
            name='endurance_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='armor',
            name='intelligence_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='armor',
            name='intelligence_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='armor',
            name='luck_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='armor',
            name='luck_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='armor',
            name='speed_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='armor',
            name='speed_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='armor',
            name='strength_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='armor',
            name='strength_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='armor',
            name='willpower_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='armor',
            name='willpower_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='rune',
            name='enhancements',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='agility_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='agility_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='weapon',
            name='charisma_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='charisma_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='weapon',
            name='endurance_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='endurance_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='weapon',
            name='intelligence_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='intelligence_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='weapon',
            name='luck_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='luck_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='weapon',
            name='speed_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='speed_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='weapon',
            name='strength_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='strength_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='weapon',
            name='willpower_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='willpower_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
