# Generated by Django 4.2.4 on 2023-11-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_weapon_item_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enhancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('power', models.IntegerField()),
                ('description', models.CharField(max_length=128)),
            ],
        ),
    ]
