# Generated by Django 4.2.4 on 2023-11-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_enhancement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enhancement',
            name='description',
            field=models.TextField(max_length=128),
        ),
    ]
