# Generated by Django 4.2.4 on 2023-11-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_enhancement_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enhancement',
            old_name='description',
            new_name='effect',
        ),
    ]
