# Generated by Django 4.2.4 on 2023-10-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_visited',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_text',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
