# Generated by Django 4.2.4 on 2023-10-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_comment_receiver_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_visited',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
