# Generated by Django 4.2.4 on 2023-10-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_visited',
        ),
    ]
