# Generated by Django 4.2.4 on 2023-10-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_last_visited'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guests',
            new_name='Guestbook',
        ),
    ]
