# Generated by Django 4.2.4 on 2023-10-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_guests_guestbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='timestamp',
            field=models.DateTimeField(default=1698516440.350304),
        ),
    ]
