# Generated by Django 4.2.4 on 2023-10-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_guestbook_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='timestamp',
            field=models.DateTimeField(default='1698516499.1239307'),
        ),
    ]
