# Generated by Django 4.2.4 on 2023-10-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_guestbook_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='timestamp',
            field=models.TimeField(default=1698516557.8867545),
        ),
    ]
