# Generated by Django 4.2.4 on 2023-10-28 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_guestbook_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(default=datetime.time),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='timestamp',
            field=models.DateTimeField(default=datetime.time),
        ),
    ]
