# Generated by Django 4.2.4 on 2023-10-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_comment_post_date_comment_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='static/avatars/placeholder.png', upload_to='static/avatars'),
        ),
    ]
