# Generated by Django 4.2.4 on 2023-11-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_account_known_recipes_remove_account_treasury_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knownrecipes',
            options={'verbose_name': 'Known recipe', 'verbose_name_plural': 'Known recipes'},
        ),
        migrations.AlterModelOptions(
            name='treasury',
            options={'verbose_name': 'Treasury', 'verbose_name_plural': 'Treasuries'},
        ),
    ]
