# Generated by Django 4.2.4 on 2023-11-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_knownrecipes_options_alter_treasury_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='item_type',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='treasury',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
