# Generated by Django 4.2.4 on 2023-10-23 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength_total', models.IntegerField(default=0)),
                ('intelligence_total', models.IntegerField(default=0)),
                ('endurance_total', models.IntegerField(default=0)),
                ('speed_total', models.IntegerField(default=0)),
                ('agility_total', models.IntegerField(default=0)),
                ('willpower_total', models.IntegerField(default=0)),
                ('charisma_total', models.IntegerField(default=0)),
                ('luck_total', models.IntegerField(default=0)),
                ('physical_armor', models.IntegerField(default=0)),
                ('magical_armor', models.IntegerField(default=0)),
                ('physical_mitigation', models.FloatField(default=0.0)),
                ('magical_mitigation', models.FloatField(default=0.0)),
                ('abilities', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=64)),
                ('zone', models.CharField(blank=True, max_length=64, null=True)),
                ('mob_type', models.CharField(default='normal', max_length=16)),
                ('race', models.CharField(blank=True, default='monster', max_length=16, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dwarf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength_total', models.IntegerField(default=0)),
                ('intelligence_total', models.IntegerField(default=0)),
                ('endurance_total', models.IntegerField(default=0)),
                ('speed_total', models.IntegerField(default=0)),
                ('agility_total', models.IntegerField(default=0)),
                ('willpower_total', models.IntegerField(default=0)),
                ('charisma_total', models.IntegerField(default=0)),
                ('luck_total', models.IntegerField(default=0)),
                ('physical_armor', models.IntegerField(default=0)),
                ('magical_armor', models.IntegerField(default=0)),
                ('physical_mitigation', models.FloatField(default=0.0)),
                ('magical_mitigation', models.FloatField(default=0.0)),
                ('abilities', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('status_time', models.DateTimeField(blank=True, null=True)),
                ('pvp_points', models.IntegerField(default=0)),
                ('battles_fought', models.IntegerField(default=0)),
                ('battles_won', models.IntegerField(default=0)),
                ('head', models.CharField(blank=True, max_length=64, null=True)),
                ('shoulders', models.CharField(blank=True, max_length=64, null=True)),
                ('chest', models.CharField(blank=True, max_length=64, null=True)),
                ('gloves', models.CharField(blank=True, max_length=64, null=True)),
                ('pants', models.CharField(blank=True, max_length=64, null=True)),
                ('boots', models.CharField(blank=True, max_length=64, null=True)),
                ('two_hand', models.CharField(blank=True, max_length=64, null=True)),
                ('main_hand', models.CharField(blank=True, max_length=64, null=True)),
                ('off_hand', models.CharField(blank=True, max_length=64, null=True)),
                ('trinket', models.CharField(blank=True, max_length=64, null=True)),
                ('strength_base', models.IntegerField(default=1)),
                ('intelligence_base', models.IntegerField(default=1)),
                ('endurance_base', models.IntegerField(default=1)),
                ('speed_base', models.IntegerField(default=1)),
                ('agility_base', models.IntegerField(default=1)),
                ('willpower_base', models.IntegerField(default=1)),
                ('charisma_base', models.IntegerField(default=1)),
                ('luck_base', models.IntegerField(default=1)),
                ('strength_multiplier', models.IntegerField(default=0)),
                ('intelligence_multiplier', models.IntegerField(default=0)),
                ('endurance_multiplier', models.IntegerField(default=0)),
                ('speed_multiplier', models.IntegerField(default=0)),
                ('agility_multiplier', models.IntegerField(default=0)),
                ('willpower_multiplier', models.IntegerField(default=0)),
                ('charisma_multiplier', models.IntegerField(default=0)),
                ('luck_multiplier', models.IntegerField(default=0)),
                ('strength_bonus', models.IntegerField(default=0)),
                ('intelligence_bonus', models.IntegerField(default=0)),
                ('endurance_bonus', models.IntegerField(default=0)),
                ('speed_bonus', models.IntegerField(default=0)),
                ('agility_bonus', models.IntegerField(default=0)),
                ('willpower_bonus', models.IntegerField(default=0)),
                ('charisma_bonus', models.IntegerField(default=0)),
                ('luck_bonus', models.IntegerField(default=0)),
                ('ability_cap', models.IntegerField(default=0)),
                ('battle_power', models.IntegerField(default=0)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
