# Generated by Django 4.2.4 on 2023-09-29 13:59

import apps.dwarves.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dwarf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('status_time', models.DateTimeField(blank=True, null=True)),
                ('PVP_points', models.IntegerField(default=0)),
                ('PVP_total', models.IntegerField(default=0)),
                ('PVP_wins', models.IntegerField(default=0)),
                ('equipment', models.JSONField(default=apps.dwarves.models.equipment)),
                ('attributes_base', models.JSONField(default=apps.dwarves.models.attributes_base)),
                ('attributes_trained', models.JSONField(default=apps.dwarves.models.attributes_trained)),
                ('attributes_multiplier', models.JSONField(default=apps.dwarves.models.attributes_multiplier)),
                ('attributes_bonus', models.JSONField(default=apps.dwarves.models.attributes_bonus)),
                ('attributes_total', models.JSONField(default=apps.dwarves.models.attributes_total)),
                ('physical_armor', models.IntegerField(default=0)),
                ('magical_armor', models.IntegerField(default=0)),
                ('physical_mitigation', models.FloatField(default=0.0)),
                ('magical_mitigation', models.FloatField(default=0.0)),
                ('ability_cap', models.IntegerField(default=0)),
                ('abilities', models.JSONField(blank=True, default=dict)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
