# Generated by Django 4.2.4 on 2023-10-25 16:35

import apps.dwarves.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwarf',
            name='agility_base',
            field=models.IntegerField(default=apps.dwarves.models.initial_attributes),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='charisma_base',
            field=models.IntegerField(default=apps.dwarves.models.initial_attributes),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='endurance_base',
            field=models.IntegerField(default=apps.dwarves.models.initial_attributes),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='intelligence_base',
            field=models.IntegerField(default=apps.dwarves.models.initial_attributes),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='luck_base',
            field=models.IntegerField(default=apps.dwarves.models.initial_attributes),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='speed_base',
            field=models.IntegerField(default=apps.dwarves.models.initial_attributes),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='strength_base',
            field=models.IntegerField(default=apps.dwarves.models.initial_attributes),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='willpower_base',
            field=models.IntegerField(default=apps.dwarves.models.initial_attributes),
        ),
    ]
