# Generated by Django 4.2.4 on 2023-10-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwarf',
            name='battle_power',
            field=models.IntegerField(default=0),
        ),
    ]
