# Generated by Django 4.2.4 on 2023-10-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0002_alter_dwarf_agility_base_alter_dwarf_charisma_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwarf',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
