# Generated by Django 4.2.4 on 2023-10-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0002_dwarf_battle_power'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dwarf',
            old_name='PVP_points',
            new_name='pvp_points',
        ),
        migrations.RenameField(
            model_name='dwarf',
            old_name='PVP_total',
            new_name='pvp_total',
        ),
        migrations.RenameField(
            model_name='dwarf',
            old_name='PVP_wins',
            new_name='pvp_wins',
        ),
    ]
