# Generated by Django 4.2.4 on 2023-10-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0003_rename_pvp_points_dwarf_pvp_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dwarf',
            old_name='pvp_total',
            new_name='battles_fought',
        ),
        migrations.RenameField(
            model_name='dwarf',
            old_name='pvp_wins',
            new_name='battles_won',
        ),
    ]
