# Generated by Django 4.2.4 on 2023-10-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0003_dwarf_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwarf',
            name='agility_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='charisma_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='endurance_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='intelligence_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='luck_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='speed_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='strength_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='willpower_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
