# Generated by Django 4.2.4 on 2023-10-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0005_alter_dwarf_options_alter_monster_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwarf',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
