# Generated by Django 4.2.4 on 2023-11-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0006_alter_dwarf_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dwarf',
            old_name='main_hand',
            new_name='weapon',
        ),
        migrations.RemoveField(
            model_name='dwarf',
            name='off_hand',
        ),
        migrations.RemoveField(
            model_name='dwarf',
            name='two_hand',
        ),
    ]
