# Generated by Django 4.2.4 on 2023-11-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarves', '0007_rename_main_hand_dwarf_weapon_remove_dwarf_off_hand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwarf',
            name='agility_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='charisma_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='endurance_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='intelligence_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='luck_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='speed_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='strength_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='dwarf',
            name='willpower_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
