# Generated by Django 4.2.4 on 2023-08-27 16:27

from django.db import migrations, models
import dwarves.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dwarf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('leader', models.TextField()),
                ('level', models.IntegerField()),
                ('attr_base', models.JSONField(default=dwarves.models.base_attributes)),
                ('attr_trained', models.JSONField(default=dwarves.models.trained_attributes)),
                ('tactic', models.TextField(default='Frenzy')),
                ('equipment', models.JSONField(default=dwarves.models.default_equipment)),
            ],
        ),
    ]
