# Generated by Django 4.2.4 on 2023-09-21 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dwarves.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dwarf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('status', models.JSONField(default=dwarves.models.default_status)),
                ('equipment', models.JSONField(default=dwarves.models.equipment)),
                ('attributes_base', models.JSONField(default=dwarves.models.attributes_base)),
                ('attributes_trained', models.JSONField(default=dwarves.models.attributes_trained)),
                ('attribute_multipliers', models.JSONField(default=dwarves.models.attribute_multipliers)),
                ('attributes_total', models.JSONField(default=dwarves.models.attributes_total)),
                ('physical_armor', models.FloatField(default=0.0)),
                ('magical_armor', models.FloatField(default=0.0)),
                ('ability_cap', models.IntegerField(default=0)),
                ('abilities', models.JSONField(blank=True, default=dict)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
